name: health_flutter
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/eterkit/flutter-packages/tree/main/health_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  pigeon: ^11.0.1
  import_sorter: ^4.6.0

flutter:
  plugin:
    platforms:
      android:
        package: com.eterkit.health_flutter
        pluginClass: HealthFlutterPlugin
      ios:
        pluginClass: HealthFlutterPlugin

import_sorter:
  comments: false
  ignored_files:
    - /pigeons/
    - /lib/src/messages/
